### ISSUE TITLE
Bootloader GUI crashes on startup

### ISSUE THREAD

**Issue by vmoravec** [yast/ycp-killer#504]
Image Version [edit]: 0006 (06-Jul-2013 21:03)

While I was trying to open the boot configuration  menu on the complete installation proposal, the installation crashed without any gui dialog or warning. Below are the logs.

y2log: http://pastebin.suse.de/7261

signal: http://pastebin.suse.de/7260

**Comment by vmoravec** [comment]
I updated the title as the issue does not affect only the installation menu, but it's the same even if started on running installed system.

In ncurses it crashes after the initial loading screen is done, but before the bootloader summary is shown.

**Comment by jreidinger** [comment]
@vmoravec can you reproduce it with recent builds? looks like problem of mixture of old ui bindings and new core.

**Comment by vmoravec** [comment]
The issue is still present (at least in ncurses ui):
- tested with the recent image Build0002 ( 09-Jul-2013 13:57 ), 
- packages updated to: 
  - `yast2-bootloader-2.24.1-13.1.x86_64`
  - `yast2-core-2.24.7-2.1.x86_64`
  - `yast2-ycp-ui-bindings-2.24.0-11.1.x86_64`
  - `yast2-ruby-bindings-1.1.4-3.1.x86_64`

**Comment by jreidinger** [comment]
fixed in https://github.com/yast/yast-bootloader/pull/18

**Comment by jsuchome** [comment]
The crash is still happening with Build0008 from 16-Jul-2013 10:15 and reportedly also with M3 edition.

**Comment by jsuchome** [comment]
The patch helps in a way, that YaST does not crash. But indeed, the dialog is empty instead. There are these lines at the end of y2log:

2013-07-16 16:17:48 <3> 10.0.0.5(5941) [Ruby] modules/CWM.rb:194 Unknown value type symbol(string,map,integer)
2013-07-16 16:17:48 <3> 10.0.0.5(5941) [Ruby] modules/CWM.rb:194 Unknown value type symbol(string,map)
2013-07-16 16:17:48 <3> 10.0.0.5(5941) [Ruby] modules/CWM.rb:194 Unknown value type symbol(string,map,integer)
2013-07-16 16:17:48 <3> 10.0.0.5(5941) [Ruby] modules/CWM.rb:194 Unknown value type symbol(string,map,integer)
2013-07-16 16:17:48 <3> 10.0.0.5(5941) [Ruby] modules/CWM.rb:194 Unknown value type symbol(string,map,boolean,integer)
2013-07-16 16:17:49 <1> 10.0.0.5(5941) [Ruby] yast/ops.rb:42 Builtin index called on nil.
2013-07-16 16:17:49 <1> 10.0.0.5(5941) [Ruby] yast/ops.rb:42 Builtin index called on nil.
2013-07-16 16:17:49 <1> 10.0.0.5(5941) [Ruby] yast/ops.rb:42 Builtin index called on nil.
2013-07-16 16:17:49 <1> 10.0.0.5(5941) [Ruby] yast/ops.rb:42 Builtin index called on nil.
2013-07-16 16:17:49 <1> 10.0.0.5(5941) [Ruby] yast/ops.rb:42 Builtin index called on nil.

CWM.rb checks the type of the variable. Why doesn't Ops.is_symbol? return true for those cases?

**Comment by jsuchome** [comment]
The reason for empty dialog: when bootloader/routines/dialogs.rb calls CWM.ShowAndRun (in MainDialog), the value of @global_handlers is nil. 
But it should be defined from included file bootloader/routines/global_widgets.rb.

**Comment by lslezak** [comment]
Fixed in https://github.com/yast/yast-ruby-bindings/pull/67 (the includes were not properly initialized when the client was started again).
